netinet/in.h is required for struct sockaddr_in
main.c:739:24: error: variable has incomplete type 'struct sockaddr_in'
    struct sockaddr_in serv_addr;